# Generated by Django 4.1.2 on 2023-06-20 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlantSitterApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='idUtilisateur',
        ),
        migrations.AddField(
            model_name='message',
            name='idDest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utdest', to='PlantSitterApp.utilisateur'),
        ),
        migrations.AddField(
            model_name='message',
            name='idsrc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utsource', to='PlantSitterApp.utilisateur'),
        ),
    ]
