# Generated by Django 4.1.2 on 2023-01-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantSitterApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='plante',
            field=models.ManyToManyField(related_name='plantes', to='PlantSitterApp.plante'),
        ),
    ]
