# Generated by Django 4.1.2 on 2023-01-31 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlantSitterApp', '0002_publication_plante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='datefin',
            new_name='dateFin',
        ),
    ]
