# Generated by Django 4.1.2 on 2023-02-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantSitterApp', '0003_rename_datefin_publication_datefin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='complement',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
