# Generated by Django 4.1.2 on 2023-02-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantSitterApp', '0004_alter_adresse_complement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plante',
            name='image',
            field=models.URLField(),
        ),
    ]
