# Generated by Django 4.1.2 on 2023-02-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantSitterApp', '0005_alter_plante_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='heureDebut',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='heureFin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='heure',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
