# Generated by Django 4.1.2 on 2023-02-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantSitterApp', '0006_publication_heuredebut_publication_heurefin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conseil',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.URLField(),
        ),
    ]
