# Generated by Django 4.1.2 on 2023-02-02 09:29

import PlantSitterApp.modeles.publication
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantSitterApp', '0009_alter_publication_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=PlantSitterApp.modeles.publication.upload_to),
        ),
    ]
