# Generated by Django 4.1.2 on 2023-02-02 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PlantSitterApp', '0010_alter_publication_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='idAccepteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepteur', to='PlantSitterApp.utilisateur'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='idCreateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='createur', to='PlantSitterApp.utilisateur'),
        ),
    ]
